### ISSUE TITLE
Survivorship Bias

### ISSUE THREAD

**Issue by tloriato** [terremoth/faculdadeTI#1]
> O viés de sobrevivência, segundo Rolf Dobelli, no livro “A arte de pensar claramente”, significa que, como no dia a dia o sucesso produz maior visibilidade do que o fracasso, você superestima sistematicamente a perspectiva de sucesso.

Não acho pertinente a lista de nomes notórios sem segundo-grau no texto pelo motivo acima. Se quisermos demonstrar a "empregabilidade" da área mesmo sem formação acho que seria mais vantajoso usar pesquisas.

**Comment by terremoth** [comment]
Fazer pesquisas para validar essas ideias é uma boa, das quais acredito estar certo, já que um empregador com consciência sã prefere alguém qualificado para a tarefa na qual o contrata independente de qual faculdade tenha ou não feito. 
Mas você está livre para criar um Google Forms ou similar para agregar ao post ou a um fork.
